# Generated by Django 4.2.7 on 2024-04-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avidoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adobjectmodel',
            options={'verbose_name': 'Объект продажи', 'verbose_name_plural': 'Объекты продаж'},
        ),
        migrations.AlterModelOptions(
            name='advertmodel',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='chatmodel',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='images',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Фотография'),
        ),
    ]
