# Generated by Django 4.2.7 on 2024-04-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avidoapp', '0002_alter_adobjectmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='images',
            new_name='image',
        ),
    ]
