# Generated by Django 4.2.7 on 2024-04-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avidoapp', '0004_user_is_block_alter_advertmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_unblock',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время разблокировки'),
        ),
    ]
