# Generated by Django 4.2.7 on 2024-04-25 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avidoapp', '0005_user_time_unblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertmodel',
            name='ad_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avidoapp.adobjectmodel', verbose_name='Объект продажи'),
        ),
        migrations.AlterField(
            model_name='advertmodel',
            name='is_displayed',
            field=models.BooleanField(default=True, verbose_name='Отображать?'),
        ),
    ]
