# Generated by Django 4.2.7 on 2024-04-30 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('avidoapp', '0006_alter_advertmodel_ad_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания сообщения'),
        ),
    ]
