# Generated by Django 4.2.7 on 2024-05-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avidoapp', '0008_alter_adobjectmodel_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adobjectmodel',
            name='body_type',
            field=models.CharField(blank=True, choices=[('Седан', 'Седан'), ('Хэтчбек', 'Хэтчбек'), ('Пикап', 'Пикап'), ('Limousine', 'Лимузин'), ('Universal', 'Универсал'), ('Minivan', 'Минивэн'), ('Coupe', 'Купе'), ('Cabriolet', 'Кабриолет')], max_length=256, null=True, verbose_name='Вид кузова'),
        ),
    ]
