# Generated by Django 4.2.7 on 2024-05-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avidoapp', '0010_alter_adobjectmodel_body_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Аватар'),
        ),
    ]
