# Generated by Django 4.2.7 on 2024-05-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avidoapp', '0011_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adobjectmodel',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='adobjectmodel',
            name='contacts',
        ),
        migrations.AddField(
            model_name='adobjectmodel',
            name='responsibilities',
            field=models.TextField(blank=True, null=True, verbose_name='Обязанности'),
        ),
        migrations.AlterField(
            model_name='adobjectmodel',
            name='body_type',
            field=models.CharField(blank=True, choices=[('Седан', 'Седан'), ('Хэтчбек', 'Хэтчбек'), ('Пикап', 'Пикап'), ('Лимузин', 'Лимузин'), ('Универсал', 'Универсал'), ('Минивэн', 'Минивэн'), ('Купе', 'Купе'), ('Кабриолет', 'Кабриолет')], max_length=256, null=True, verbose_name='Вид кузова'),
        ),
        migrations.AlterField(
            model_name='adobjectmodel',
            name='car_make',
            field=models.CharField(max_length=256, null=True, verbose_name='Марка машины'),
        ),
        migrations.AlterField(
            model_name='adobjectmodel',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель'), ('Пропан', 'Пропан'), ('Электричество', 'Электричество')], max_length=256, null=True, verbose_name='Вид топлива'),
        ),
        migrations.AlterField(
            model_name='adobjectmodel',
            name='job_title',
            field=models.CharField(max_length=256, null=True, verbose_name='Название вакансии'),
        ),
        migrations.AlterField(
            model_name='adobjectmodel',
            name='property_type',
            field=models.CharField(choices=[('Квартира', 'Квартира'), ('Дом', 'Дом'), ('Прочее', 'Прочее')], max_length=256, null=True, verbose_name='Тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='adobjectmodel',
            name='state',
            field=models.CharField(blank=True, choices=[('Первичное жилье', 'Первичное жилье'), ('Вторичное жилье', 'Вторичное жилье')], max_length=256, null=True, verbose_name='Состояние'),
        ),
    ]
